const std = @import("std");

pub fn render(writer: *std.Io.Writer, include_dir: []const u8, sys_include_dir: []const u8, crt_dir: []const u8) !void {
    const installation: std.zig.LibCInstallation = .{
        .include_dir = include_dir,
        .sys_include_dir = sys_include_dir,
        .crt_dir = crt_dir,
        .cc_dir = crt_dir,
    };
    try writer.writeAll("# Generated by zig-android-sdk. DO NOT EDIT.\n");
    try installation.render(writer);
}

test "Android libc metadata round trips through the compiler parser" {
    var buffer: [4096]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buffer);
    try render(&writer, "ndk/usr/include", "ndk/usr/include/aarch64-linux-android", "ndk/usr/lib/aarch64-linux-android/35");
    const file = "sdk-libc-config-test.conf";
    try std.Io.Dir.cwd().writeFile(std.testing.io, .{ .sub_path = file, .data = writer.buffered() });
    defer std.Io.Dir.cwd().deleteFile(std.testing.io, file) catch {};
    const target = try std.zig.system.resolveTargetQuery(std.testing.io, .{
        .cpu_arch = .aarch64,
        .os_tag = .linux,
        .abi = .android,
    });
    var parsed = try std.zig.LibCInstallation.parse(std.testing.allocator, std.testing.io, file, &target);
    defer parsed.deinit(std.testing.allocator);
    try std.testing.expectEqualStrings("ndk/usr/lib/aarch64-linux-android/35", parsed.crt_dir.?);
    try std.testing.expectEqualStrings(parsed.crt_dir.?, parsed.cc_dir.?);
}
